// Package models defines all shared message structures exchanged over the IPC
// protocol (Python ↔ Go) and over the P2P WebRTC DataChannel (Go ↔ Go).
//
// Wire format (IPC, TCP localhost:1488):
//
//	┌──────────────────────┬──────────────────────────────────┐
//	│  Length (4 bytes BE) │  Payload (N bytes)               │
//	└──────────────────────┴──────────────────────────────────┘
//
// The payload is either a UTF-8 JSON object or a raw binary encrypted chunk.
// Go uses json.Unmarshal to distinguish them: success → control message,
// failure → encrypted chunk to be forwarded as-is.
package models

import "encoding/json"

// ---------------------------------------------------------------------------
// Enumerations
// ---------------------------------------------------------------------------

// MessageType identifies which IPC control message is being sent.
type MessageType string

const (
	// TypeMetadata is sent by the Python sender before the file transfer begins.
	TypeMetadata MessageType = "metadata"

	// TypeReady is sent by the Python receiver once it accepts the file and
	// initialises its decryptor. Go forwards it to the sender's Python.
	TypeReady MessageType = "ready"

	// TypeError is sent by either Python side when something goes wrong.
	// Go must forward it to the other peer and may also emit it itself.
	TypeError MessageType = "error"

	// TypeStatus is generated exclusively by Go to report P2P connection
	// state changes back to the local Python client.
	TypeStatus MessageType = "status"

	// TypeConnect is sent by Python to Go to instruct it to establish a P2P
	// connection using the supplied peer code and role.
	// NOTE: This message type is not yet in the Python codebase; see INTERFACE.md.
	TypeConnect MessageType = "connect"

	// TypeSignal is an optional passthrough for raw SDP / ICE-candidate JSON.
	// Go handles the WebRTC negotiation internally; this type exists for
	// diagnostic / manual-override use cases.
	TypeSignal MessageType = "signal"
)

// StatusValue is the value carried inside a StatusMsg.
type StatusValue string

const (
	// StatusConnecting is emitted by Go right after the P2P handshake starts.
	StatusConnecting StatusValue = "connecting"

	// StatusConnected is emitted by Go when the WebRTC DataChannel opens.
	StatusConnected StatusValue = "connected"

	// StatusDisconnected is emitted by Go when the P2P connection closes.
	StatusDisconnected StatusValue = "disconnected"

	// StatusFinished is emitted by the receiver's Go when all chunks have
	// been forwarded to Python (i.e., the transfer is complete).
	StatusFinished StatusValue = "finished"

	// StatusError is emitted by Go when an internal (non-transfer) error occurs.
	StatusError StatusValue = "error"
)

// Role determines the WebRTC negotiation posture of this Go instance.
type Role string

const (
	// RoleSender acts as the WebRTC offerer and the file-data originator.
	RoleSender Role = "sender"

	// RoleReceiver acts as the WebRTC answerer and the file-data consumer.
	RoleReceiver Role = "receiver"
)

// ---------------------------------------------------------------------------
// IPC Message structs  (Python ↔ Go)
// ---------------------------------------------------------------------------

// BaseMessage is used only for type-switching: unmarshal the raw payload into
// BaseMessage first, inspect Type, then unmarshal again into the concrete type.
type BaseMessage struct {
	Type MessageType `json:"type"`
}

// MetadataMsg is sent by the Python sender before chunks begin flowing.
//
//	{"type":"metadata","name":"archive.zip","size":104857600}
type MetadataMsg struct {
	Type MessageType `json:"type"`
	Name string      `json:"name"`
	Size int64       `json:"size"`
}

// ReadyMsg is sent by the Python receiver after the user accepts the transfer
// and the AES-256-GCM decryptor has been initialised successfully.
//
//	{"type":"ready"}
type ReadyMsg struct {
	Type MessageType `json:"type"`
}

// ErrorMsg is sent by either Python client when a fatal error occurs.
// Go forwards it to the remote peer and may also generate it internally.
//
//	{"type":"error","msg":"Wrong Password or PIN mismatch"}
type ErrorMsg struct {
	Type MessageType `json:"type"`
	Msg  string      `json:"msg"`
}

// StatusMsg is generated by Go and sent to the local Python client to report
// the current state of the P2P layer.
//
//	{"type":"status","value":"connected"}
type StatusMsg struct {
	Type  MessageType `json:"type"`
	Value StatusValue `json:"value"`
}

// ConnectMsg is sent by Python to Go to initiate NAT traversal.
// The peer code doubles as the signaling session ID.
//
//	{"type":"connect","code":"123-456","role":"sender"}
type ConnectMsg struct {
	Type MessageType `json:"type"`
	// Code is the 6-digit peer code in "XXX-XXX" format generated by the sender.
	// It is used both as the signaling session key and as the PBKDF2 salt on
	// the Python side (Go never sees the raw encryption key).
	Code string `json:"code"`
	// Role is either "sender" (WebRTC offerer) or "receiver" (WebRTC answerer).
	Role Role `json:"role"`
}

// SignalMsg optionally carries raw WebRTC SDP or ICE-candidate data over IPC.
// Under normal operation Go handles all WebRTC negotiation internally; this
// message exists for transparency, debugging, and advanced configurations.
//
//	{"type":"signal","sdp":"v=0...","sdp_type":"offer"}
type SignalMsg struct {
	Type          MessageType `json:"type"`
	SDPType       string      `json:"sdp_type,omitempty"`       // "offer" | "answer"
	SDP           string      `json:"sdp,omitempty"`            // full SDP blob
	Candidate     string      `json:"candidate,omitempty"`      // ICE candidate string
	SDPMid        string      `json:"sdp_mid,omitempty"`        // ICE mid
	SDPMLineIndex uint16      `json:"sdp_mline_index,omitempty"` // ICE m-line index
}

// ---------------------------------------------------------------------------
// P2P envelope  (Go ↔ Go over WebRTC DataChannel)
// ---------------------------------------------------------------------------

// P2PEnvelope wraps every message that travels over the WebRTC DataChannel.
// Text frames (dc.SendText) carry JSON-encoded P2PEnvelope values; binary
// frames (dc.Send) carry raw encrypted chunk bytes without any envelope.
//
// Using the WebRTC DataChannel's native text/binary distinction lets Go avoid
// the fragile UTF-8 heuristic that Python currently uses over TCP.
type P2PEnvelope struct {
	Type    MessageType     `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// ---------------------------------------------------------------------------
// Chunk constants
// ---------------------------------------------------------------------------

const (
	// ChunkPlaintextMax is the maximum number of plaintext bytes per chunk.
	ChunkPlaintextMax = 64 * 1024 // 64 KiB

	// ChunkNonceSize is the AES-256-GCM nonce length prepended by Python.
	ChunkNonceSize = 12

	// ChunkGCMTagSize is the GCM authentication tag appended by Python's AESGCM.
	ChunkGCMTagSize = 16

	// ChunkMaxEncryptedSize is the maximum total size of one encrypted chunk
	// as it arrives over the wire: nonce + ciphertext + GCM tag.
	ChunkMaxEncryptedSize = ChunkNonceSize + ChunkPlaintextMax + ChunkGCMTagSize // 65 564 bytes
)

// ---------------------------------------------------------------------------
// Constructor helpers
// ---------------------------------------------------------------------------

// NewStatus returns a StatusMsg ready for JSON encoding.
func NewStatus(v StatusValue) StatusMsg {
	return StatusMsg{Type: TypeStatus, Value: v}
}

// NewError returns an ErrorMsg ready for JSON encoding.
func NewError(msg string) ErrorMsg {
	return ErrorMsg{Type: TypeError, Msg: msg}
}

// NewReady returns a ReadyMsg ready for JSON encoding.
func NewReady() ReadyMsg {
	return ReadyMsg{Type: TypeReady}
}
